### ISSUE TITLE
Contato

### ISSUE THREAD

**Issue by SoftwrDev** [echoarison/ExFxClassAndMethodAbst#1]
Opa cara tudo bem?
Estou tentando encontrar seu contato mas não estou achando.
Queria conversar contigo.
Pode me mandar seu e-mail ou algo do tipo por aqui?

**Comment by echoarison** [comment]
Opa mano, esta tudo bem comigo e você ?
Cara posso te passar sim, mas eu creio que tenho você ainda no Whatzap e posso enviar mensagem.
O meu e-mail é patricalison2017@gmail.com
